### ISSUE TITLE
Update Instructions for Docker 

### ISSUE THREAD

**Issue by rbinrais** [decentralized-identity/ion#103]
While configuring ION using instructions for [docker](https://github.com/decentralized-identity/ion/tree/master/docker) I notice that the service names for ```ion-ipfs``` and ```ion-bitcoin``` within the docker-compose files are not correct. Renaming them 

Also, in ```config.sh```,  the path used to probe the bitcoin sync progress [in line 48 ](https://github.com/decentralized-identity/ion/blob/master/docker/config.sh#L48 ) is missing ```/data``` in the path 
* Issue: ```  PROGRESS=`sudo tail -n 1 /datadrive/testnet3/debug.log | grep -Po 'progress=\K.*?(.{5})\s'` ```. 
* Fix: ``` PROGRESS=`sudo tail -n 1 /datadrive/testnet3/debug.log | grep -Po 'progress=\K.*?(.{5})\s'` ```

docker-compose.yml
```
version: "3"
services:
  bitcoin-core:
    container_name: bitcoin-core
    image: ruimarinho/bitcoin-core:0.19.1-alpine
    command:
      -printtoconsole
      -testnet=1
      -txindex=1
      -server=1
    environment:
      - BITCOIN_DATA=/data
    volumes:
      - ${DATA_VOL}:/data
  bitcoin-ion:
    container_name: ion-bitcoin
    image: node:10.20.1-alpine3.11
    command: "npm run bitcoin"
    working_dir: /ion
    links:
      - "bitcoin-core"
      - "mongo"
    volumes:
      - ./ion:/ion
  ipfs:
    container_name: ion-ipfs
    image: node:10.20.1-alpine3.11
    command: "npm run ipfs"
    working_dir: /ion
    depends_on:
      - "ion-bitcoin"
    volumes:
      - ./ion:/ion
  core:
    container_name: ion-core
    image: node:10.20.1-alpine3.11
    command: "npm run core"
    working_dir: /ion
    links:
      - "ion-bitcoin"
      - "ion-ipfs"
      - "mongo"
    volumes:
      - ./ion:/ion
  mongo:
    container_name: mongo
    image: mongo:3.6.18-xenial
    volumes:
      - ${DB_VOL}:/data/db
```
